version: '3'

services:
  web:
    build: .
    command: gunicorn loginSignUp.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=loginSignUp.settings
